name: Node Continuous Integration

on:
  pull_request:
    branches: [ master, dev, staging ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: echo ${{ github.base_ref }}
